---
title: Quarto style for Uni Freiburg presentations
footer: Dr. Thilo Wiertz | Economic Geography and Sustainable Development | 2024
author: 
  name: "Dr. Thilo Wiertz"
  affiliation: "Economic Geography and Sustainable Development"
  email: "thilo.wiertz@geographie.uni-freiburg.de"
date: last-modified
format: ufr-revealjs
---

## About this project

- Quarto converts markdown content to various output formats
- This style is based on the [revealjs](https://revealjs.com) presentation format
- It implements [corporate design principles](https://cd.uni-freiburg.de) of the University of Freiburg


## Formatting examples
### You can add subtitles as third level headlines

Adding a div by using `::: {.spacer}` creates a blank space.

::: {.spacer}
:::

So this line is set apart from the one before.

## A single column slide

Text before a list is emphasized automatically

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3

## Highlights

To highlight a piece of text, put it in a div:

::: {.highlight-pink}
`::: {.highlight-pink}`
:::

::: {.highlight-green}
`::: {.highlight-green}`
:::

::: {.highlight-yellow}
`::: {.highlight-yellow}`
:::

## Flex columns

Use `::: {.flex-col-2}` to flow content into two columns:

::: {.spacer}
:::

::: {.flex-col-2}

::: {}
Lorem Ipsum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

:::

## Flex columns

Use `::: {.flex-col-3}` to flow content into three columns:

::: {.spacer}
:::

::: {.flex-col-3}

::: {}
Lorem Ipsum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::


::: {}
Lorem Ipsum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Ipsum

- Lorem ipsum 3
- Lorem ipsum 1
- Lorem ipsum 2
:::


::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

::: {}
Lorem Isum

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::

:::

## Compact lines

Use `::: {.compact}` to reduce line height:

::: {.spacer}
:::

::: {.compact}
Sometimes stuff should be more compact:

- Lorem ipsum 1
- Lorem ipsum 2
- Lorem ipsum 3
:::


## Styles {type=task}

Wha youThis is another style used to present tasks.

1. Please do this first.
2. Then move on to this.
3. And finally, write it all down.

## Conclusion {type=conclusion}

This concludes the style. If you have questions or comments, please contact me at [thilo.wiertz@geographie.uni-freiburg.de](mailto:thilo.wiertz@geographie.uni-freiburg.de).
